'use client'

import { motion } from 'framer-motion'
import {
  ArrowRight, BarChart3, Bell, BrainCircuit, Check, ChevronDown, CircleDollarSign, Clock3,
  Download, FileSpreadsheet, Layers3, Menu, Moon, Package, Pill, ReceiptIndianRupee,
  Search, ShieldCheck, Sparkles, Sun, Truck, Users, X, Zap,
} from 'lucide-react'
import { useState } from 'react'

const features = [
  { icon: ReceiptIndianRupee, title: 'Smart Billing', text: 'GST-ready billing that stays fast at the counter, even during the rush.' },
  { icon: Package, title: 'Inventory Management', text: 'Know what is in stock, what is moving, and what needs attention.' },
  { icon: Truck, title: 'Purchase Management', text: 'Track orders, invoices, batches, and supplier dues in one place.' },
  { icon: Users, title: 'Supplier Management', text: 'Keep supplier details, credit terms, and purchase history organized.' },
  { icon: CircleDollarSign, title: 'Customer & Udhaar', text: 'Simple ledgers and reminders for every outstanding payment.' },
  { icon: BarChart3, title: 'Sales & Profit Analytics', text: 'Turn every bill into a clear view of how your store is performing.' },
  { icon: FileSpreadsheet, title: 'Reports & Data Export', text: 'Export structured JSON, Excel, and CSV data for accounting workflows.' },
  { icon: Bell, title: 'Smart Notifications', text: 'Get timely alerts for low stock, expiry, payments, and more.' },
]

const aiQuestions = ['Which medicines expire in the next 30 days?', 'How much did I sell this month?', 'Who has pending payments?']

function Logo() {
  return <a href="#top" className="flex items-center gap-3" aria-label="MSM home"><span className="logo-mark"><Pill size={19} strokeWidth={2.5} /></span><span className="text-lg font-bold tracking-tight">MSM<span className="text-primary">.</span></span></a>
}

function DashboardPreview() {
  return <div className="dashboard-window shadow-2xl">
    <div className="dashboard-top"><div className="flex items-center gap-2"><span className="window-dot bg-red-400" /><span className="window-dot bg-amber-400" /><span className="window-dot bg-emerald-400" /></div><div className="dashboard-search"><Search size={12} /> Search anything</div><span className="avatar">RK</span></div>
    <div className="dashboard-body">
      <aside className="dashboard-side"><div className="side-brand"><span className="logo-mark small"><Pill size={13} /></span> MSM</div>{['Overview', 'Billing', 'Inventory', 'Purchases', 'Customers', 'Reports'].map((item, i) => <div className={`side-item ${i === 0 ? 'active' : ''}`} key={item}><span className="side-icon">{[BarChart3, ReceiptIndianRupee, Package, Truck, Users, FileSpreadsheet][i] && (() => { const Icon = [BarChart3, ReceiptIndianRupee, Package, Truck, Users, FileSpreadsheet][i]; return <Icon size={13} /> })()}</span>{item}</div>)}<div className="side-bottom"><ShieldCheck size={13} /> Protected</div></aside>
      <div className="dashboard-content"><div className="flex items-start justify-between"><div><p className="eyebrow">Tuesday, 10 September 2026</p><h3 className="dash-title">Good morning, Rajesh</h3></div><button className="icon-button"><Bell size={15} /></button></div>
        <div className="metric-grid">{[['₹2,48,560','Total sales','+18.4%', 'blue'], ['₹38,420','Estimated profit','+12.8%', 'violet'], ['1,284','Bills this month','+9.2%', 'green'], ['₹12,800','Outstanding','-6.4%', 'amber']].map(([value, label, change, color]) => <div className="metric-card" key={label}><div className={`metric-icon ${color}`}><BarChart3 size={14} /></div><p>{label}</p><strong>{value}</strong><span className={change.startsWith('-') ? 'negative' : 'positive'}>{change}</span></div>)}</div>
        <div className="dashboard-columns"><div className="chart-card"><div className="flex items-center justify-between"><div><p className="card-label">Sales overview</p><strong className="card-number">₹2,48,560</strong></div><span className="chart-pill">Last 6 months <ChevronDown size={11} /></span></div><div className="chart-area"><div className="chart-y"><span>₹2.5L</span><span>₹1.5L</span><span>₹50K</span><span>₹0</span></div><svg viewBox="0 0 500 150" preserveAspectRatio="none" className="sales-chart"><defs><linearGradient id="area" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="var(--primary)" stopOpacity=".22" /><stop offset="1" stopColor="var(--primary)" stopOpacity="0" /></linearGradient></defs><path d="M0,125 C35,110 55,118 85,90 S135,100 170,78 S220,88 250,62 S300,72 330,43 S380,64 415,35 S455,49 500,18 L500,150 L0,150Z" fill="url(#area)" /><path d="M0,125 C35,110 55,118 85,90 S135,100 170,78 S220,88 250,62 S300,72 330,43 S380,64 415,35 S455,49 500,18" fill="none" stroke="var(--primary)" strokeWidth="3" strokeLinecap="round" /></svg></div><div className="chart-x"><span>Apr</span><span>May</span><span>Jun</span><span>Jul</span><span>Aug</span><span>Sep</span></div></div>
          <div className="mini-card"><div className="flex items-center justify-between mb-3"><p className="card-label">AI insights</p><Sparkles size={15} className="text-primary" /></div><div className="insight"><span className="insight-dot green-dot" /><div><strong>Great momentum</strong><p>Sales are up 18.4% from last month.</p></div></div><div className="insight"><span className="insight-dot amber-dot" /><div><strong>Action needed</strong><p>12 batches expire in the next 30 days.</p></div></div><button className="mini-link">View all insights <ArrowRight size={12} /></button></div></div>
      </div>
    </div>
  </div>
}

function AiChat() {
  const [selected, setSelected] = useState(aiQuestions[0])
  return <div className="ai-chat-window"><div className="chat-head"><div className="ai-avatar"><Sparkles size={18} /></div><div><strong>MSM Assistant</strong><p>Always here to help</p></div><span className="online-dot" /></div><div className="chat-body"><div className="bubble user-bubble">{selected}</div><div className="bubble ai-bubble"><div className="flex items-center gap-2 mb-2"><span className="mini-ai"><Sparkles size={11} /></span><strong>MSM Assistant</strong></div>{selected.startsWith('Which') ? <><p>Here&apos;s the list for the next <strong>30 days</strong>:</p><div className="response-grid"><div><span>Near-expiry batches</span><strong>12</strong></div><div><span>Priority</span><strong className="text-amber-500">Review now</strong></div></div><p className="mt-3">I found 12 batches, including <strong>Azithromycin 500mg</strong> and <strong>Insulin Glargine</strong>. Want me to make a purchase or discount list?</p></> : <><p>Here&apos;s your update for <strong>September 2026</strong>:</p><div className="response-grid"><div><span>Total sales</span><strong>₹2,48,560</strong></div><div><span>vs. last month</span><strong className="text-emerald-500">+18.4%</strong></div></div><p className="mt-3">Your sales are trending well. The strongest category is <strong>Cardiovascular</strong>, up 24% this month.</p></>}</div><div className="typing"><span /><span /><span /> MSM is thinking</div></div><div className="suggestions">{aiQuestions.map(q => <button key={q} onClick={() => setSelected(q)}>{q}</button>)}</div><div className="chat-input">Ask anything about your store... <ArrowRight size={15} /></div></div>
}

function SectionHeader({ eyebrow, title, text, center = false }: { eyebrow: string; title: string; text: string; center?: boolean }) { return <div className={`section-header ${center ? 'text-center mx-auto' : ''}`}><span className="eyebrow accent">{eyebrow}</span><h2>{title}</h2><p>{text}</p></div> }

export default function Page() {
  const [dark, setDark] = useState(false)
  const [menu, setMenu] = useState(false)
  return <main id="top" className={dark ? 'dark' : ''}>
    <nav className="nav-shell"><div className="container nav-inner"><Logo /><div className={`nav-links ${menu ? 'open' : ''}`}><a href="#features" onClick={() => setMenu(false)}>Features</a><a href="#assistant" onClick={() => setMenu(false)}>AI Assistant</a><a href="#analytics" onClick={() => setMenu(false)}>Analytics</a><a href="#reports" onClick={() => setMenu(false)}>Reports</a><a href="#pricing" onClick={() => setMenu(false)}>Pricing</a><div className="mobile-actions"><a href="#pricing">Log in</a><a className="button primary" href="#pricing">Get started <ArrowRight size={15} /></a></div></div><div className="nav-actions"><button className="theme-toggle" onClick={() => setDark(!dark)} aria-label="Toggle theme">{dark ? <Sun size={16} /> : <Moon size={16} />}</button><a className="login-link" href="#pricing">Log in</a><a className="button primary nav-cta" href="#pricing">Get started <ArrowRight size={15} /></a><button className="menu-toggle" onClick={() => setMenu(!menu)} aria-label="Toggle menu">{menu ? <X /> : <Menu />}</button></div></div></nav>
    <section className="hero-section"><div className="hero-grid" /><div className="container hero-content"><motion.div initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .6 }} className="hero-copy"><div className="announcement"><span className="announcement-dot" /> Built for Pharmacy Stores</div><h1>Run your medical store <span>smarter with AI.</span></h1><p>MSM gives your store one clear place for billing, stock, purchases, and reports. Ask a question in plain words and get a useful answer right away.</p><div className="hero-actions"><a className="button primary large" href="#pricing">Start free <ArrowRight size={17} /></a><a className="button ghost large" href="#analytics">Book a demo <ArrowRight size={17} /></a></div><div className="hero-proof"><div className="avatar-stack"><span>RK</span><span>AS</span><span>MP</span><span>+</span></div><p>Trusted by <strong>2,000+</strong> pharmacy owners</p></div></motion.div><motion.div initial={{ opacity: 0, y: 25, scale: .98 }} animate={{ opacity: 1, y: 0, scale: 1 }} transition={{ duration: .8, delay: .12 }} className="hero-dashboard"><div className="dashboard-glow" /><DashboardPreview /><div className="float-card float-card-one"><div className="float-icon green"><Check size={14} /></div><div><strong>Inventory synced</strong><span>Just now</span></div></div><div className="float-card float-card-two"><Sparkles size={14} className="text-primary" /><span>AI insight ready</span></div></motion.div></div></section>
    <section className="trust-bar"><div className="container trust-inner"><div className="trust-intro"><span className="eyebrow">Built for Pharmacy Stores</span><strong>Trusted by teams who keep care moving</strong></div><div className="partner-list" aria-label="Trusted healthcare partners"><span>Client Labs</span><span>Chandra Healthcare and Diagnostics</span><span>Sultanpur</span></div></div></section>
    <section className="problem-section section-pad"><div className="container"><div className="split-heading"><SectionHeader eyebrow="The old way of working" title="Your pharmacy deserves more than a pile of spreadsheets." text="When every task lives in a different notebook or app, the small gaps become expensive problems." /><div className="problem-list">{['Manual stock counts and surprise stockouts', 'Expired medicines hiding in the back of the shelf', 'Slow billing when the counter gets busy', 'Udhaar and supplier payments slipping through', 'Reports that take hours to put together', 'No clear picture of what is driving profit'].map((x, i) => <div className="problem-item" key={x}><span>0{i + 1}</span>{x}<X size={15} /></div>)}</div></div><div className="solution-banner"><div><span className="eyebrow accent">One clear system</span><h3>Meet the operating system for your medical store.</h3></div><p>MSM brings billing, inventory, purchases, customers, reports, and intelligence together — so you can spend less time managing the store and more time growing it.</p><a className="button light" href="#features">See how it works <ArrowRight size={15} /></a></div></div></section>
    <section id="features" className="section-pad features-section"><div className="container"><SectionHeader center eyebrow="Everything in one place" title="The tools to keep your store moving." text="MSM replaces disconnected systems with one calm, capable workspace for your entire pharmacy." /><div className="feature-grid">{features.map(({ icon: Icon, title, text }, i) => <motion.div whileHover={{ y: -5 }} transition={{ duration: .2 }} className="feature-card" key={title}><div className="feature-icon"><Icon size={20} /></div><h3>{title}</h3><p>{text}</p><span className="feature-arrow"><ArrowRight size={15} /></span></motion.div>)}</div></div></section>
    <section id="assistant" className="section-pad assistant-section"><div className="container assistant-layout"><div><SectionHeader eyebrow="Plain-language help" title="Ask it like you would ask a person." text="No reports to decode. Ask MSM Assistant a simple question and get the list, number, or next step you need." /><div className="benefit-list"><div><span><Sparkles size={16} /></span><p><strong>Understand trends</strong><br />See what changed and why it matters.</p></div><div><span><Zap size={16} /></span><p><strong>Act with confidence</strong><br />Get recommendations grounded in your data.</p></div><div><span><BarChart3 size={16} /></span><p><strong>Make every day better</strong><br />Build a smarter store, one insight at a time.</p></div></div></div><AiChat /></div></section>
    <section id="analytics" className="section-pad analytics-section"><div className="container"><div className="analytics-head"><SectionHeader eyebrow="Clarity at a glance" title="Know what is happening in your business." text="From the first bill of the day to your month-end review, MSM keeps the important numbers visible." /><div className="analytics-tabs"><span className="active">Overview</span><span>Sales</span><span>Inventory</span></div></div><DashboardPreview /></div></section>
    <section className="section-pad inventory-section"><div className="container inventory-layout"><div><SectionHeader eyebrow="Inventory intelligence" title="Don&apos;t just track your stock. Understand it." text="MSM helps you make better inventory decisions before a product becomes a problem." /><a className="text-link" href="#pricing">Explore inventory tools <ArrowRight size={15} /></a></div><div className="inventory-board"><div className="inventory-item highlight"><span className="inventory-icon red"><Bell size={16} /></span><div><strong>Near expiry</strong><p>12 batches need attention</p></div><span className="inventory-value">12</span></div><div className="inventory-item"><span className="inventory-icon amber"><Package size={16} /></span><div><strong>Low stock</strong><p>18 products below threshold</p></div><span className="inventory-value">18</span></div><div className="inventory-item"><span className="inventory-icon blue"><Zap size={16} /></span><div><strong>Fast moving</strong><p>Paracetamol 500mg leads today</p></div><span className="inventory-value">+32%</span></div><div className="inventory-item"><span className="inventory-icon violet"><Layers3 size={16} /></span><div><strong>Stock valuation</strong><p>Current inventory at cost</p></div><span className="inventory-value">₹8.4L</span></div></div></div></section>
    <section id="reports" className="section-pad reports-section"><div className="container reports-layout"><div className="report-card"><div className="report-top"><span className="file-icon"><FileSpreadsheet size={18} /></span><div><strong>Monthly business report</strong><p>September 2026 · MSM export</p></div><Download size={17} className="text-muted-foreground" /></div><div className="report-lines"><span /><span /><span /><span /></div><div className="report-total"><span>Net profit this month</span><strong>₹38,420</strong></div><div className="export-row"><span>Available formats</span><span className="format">JSON</span><span className="format">XLSX</span><span className="format">CSV</span></div></div><SectionHeader eyebrow="Reports that make sense" title="Your data, ready for decisions." text="Organize sales, purchases, expenses, and tax data into reports you can actually use. Export structured files for your accountant or your next review." /></div></section>
    <section className="section-pad steps-section"><div className="container"><SectionHeader center eyebrow="Simple from day one" title="From setup to smarter decisions." text="No complicated rollout. Just a clear path to a better-run pharmacy." /><div className="steps-grid">{['Add your pharmacy', 'Add products & suppliers', 'Start billing', 'Inventory updates automatically', 'AI analyzes your business', 'Generate reports'].map((step, i) => <div className="step" key={step}><span>{String(i + 1).padStart(2, '0')}</span><div><h3>{step}</h3><p>{['Set up your store details in minutes.', 'Import your catalogue or add as you go.', 'Fast, GST-ready billing at the counter.', 'Every sale keeps stock accurate.', 'Ask questions and get useful answers.', 'Stay ready for every business review.'][i]}</p></div></div>)}</div></div></section>
    <section id="pricing" className="section-pad pricing-section"><div className="container"><SectionHeader center eyebrow="Pricing that grows with you" title="Start simple. Scale with confidence." text="Try MSM free. Upgrade when your pharmacy is ready for more power." /><div className="pricing-grid">{[['Starter', 'For getting your first store organized', '₹499', ['Smart billing', 'Basic inventory', 'Customer ledgers', 'Monthly reports']], ['Professional', 'For growing pharmacies that want clarity', '₹999', ['Everything in Starter', 'AI Assistant', 'Advanced analytics', 'Expiry & stock alerts', 'Data exports']], ['Business', 'For teams and multi-store operators', 'Custom', ['Everything in Professional', 'Multi-store dashboard', 'Priority support', 'Custom workflows']]].map(([name, desc, price, perks], i) => <motion.div whileHover={{ y: -8 }} transition={{ duration: .22, ease: 'easeOut' }} className={`price-card ${i === 1 ? 'popular' : ''}`} key={name}>{i === 1 && <span className="popular-tag">Most popular</span>}<p className="price-kicker">{name}</p><h3>{desc}</h3><div className="price"><strong>{price}</strong>{price !== 'Custom' && <span>/ month</span>}</div><a className={`button ${i === 1 ? 'primary' : 'outline'} full`} href="#top">{price === 'Custom' ? 'Talk to us' : 'Start free'} <ArrowRight size={15} /></a><div className="perks">{(perks as string[]).map(p => <span key={p}><Check size={14} /> {p}</span>)}</div></motion.div>)}</div></div></section>
    <section className="final-cta section-pad"><div className="container final-box"><div><span className="eyebrow light-eyebrow">The smarter way forward</span><h2>Your pharmacy. Your data.<br /><span>Your AI assistant.</span></h2></div><div><p>Every great pharmacy runs on trust, speed, and good decisions. MSM brings all three together.</p><a className="button light large" href="#pricing">Start using MSM <ArrowRight size={17} /></a></div></div></section>
    <footer><div className="container footer-top"><div><Logo /><p className="footer-tagline">The intelligent operating system<br />for modern medical stores.</p></div><div className="footer-links"><div><strong>Product</strong><a href="#features">Features</a><a href="#assistant">AI Assistant</a><a href="#analytics">Analytics</a><a href="#pricing">Pricing</a></div><div><strong>Company</strong><a href="#top">About MSM</a><a href="#top">Contact</a><a href="#top">Help center</a><a href="#top">Careers</a></div><div><strong>Legal</strong><a href="#top">Privacy policy</a><a href="#top">Terms of use</a><a href="#top">Security</a></div></div></div><div className="container footer-bottom"><span>© 2026 MSM Technologies. Built for Indian pharmacies.</span><span>Made for better business.</span></div></footer>
  </main>
}
